version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: balancex_frontend
    ports:
      - "127.0.0.1:5173:5173"
    restart: unless-stopped
    networks:
      - balancex_net

networks:
  balancex_net:
    driver: bridge
