[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "BHdQMss1NL2AQGVmsrpyUfmp4o7XC5X9E5ZiXitsdGNx"
smart_wallet = "CikLi2FgfnAoDDepVRe8WA7SsEHvpaJeZv5WpbvvQKCw"

[programs.devnet]
vault = "BHdQMss1NL2AQGVmsrpyUfmp4o7XC5X9E5ZiXitsdGNx"
smart_wallet = "CikLi2FgfnAoDDepVRe8WA7SsEHvpaJeZv5WpbvvQKCw"

[programs.mainnet]
vault = "BHdQMss1NL2AQGVmsrpyUfmp4o7XC5X9E5ZiXitsdGNx"
smart_wallet = "CikLi2FgfnAoDDepVRe8WA7SsEHvpaJeZv5WpbvvQKCw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
